name: auto_benchmark
on:  
  pull_request:    
    branches:
    - main  
  push:
    branches:
    - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: scope out
        run: |
            pwd
            ls
      - name: Build and test with Docker
        run: |
            docker build --tag nuc_data_maker .
            ls
            pwd
            docker run -v /home/runner/work/example-process-and-commit-using-actions-and-git-lfs/example-process-and-commit-using-actions-and-git-lfs:/share nuc_data_maker bash run_all.sh
      - name: scope out 2
        run: |
            pwd
            ls
            ls nndc-b7.1-hdf5
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add nndc-b7.1-hdf5/neutron/*.h5
          git add nndc-b7.1-hdf5/photon/*.h5
          git commit -m "Added h5 cross sections as commit" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
